export const DO_LOGIN_REQUEST = "DO_LOGIN_REQUEST"
export const DO_LOGIN_SUCCESS = "DO_LOGIN_SUCCESS"
export const DO_LOGIN_FAILURE = "DO_LOGIN_FAILURE"

export const DO_SIGNUP_REQUEST = "DO_SIGNUP_REQUEST"
export const DO_SIGNUP_SUCCESS = "DO_SIGNUP_SUCCESS"
export const DO_SIGNUP_FAILURE = "DO_SIGNUP_FAILURE"

export const ON_FORGOT_PASSWORD_REQUEST = "ON_FORGOT_PASSWORD_REQUEST"
export const ON_FORGOT_PASSWORD_SUCCESS = "ON_FORGOT_PASSWORD_SUCCESS"
export const ON_FORGOT_PASSWORD_FAILURE = "ON_FORGOT_PASSWORD_FAILURE"

export const ON_RESET_PASSWORD_REQUEST = "ON_RESET_PASSWORD_REQUEST"
export const ON_RESET_PASSWORD_SUCCESS = "ON_RESET_PASSWORD_SUCCESS"
export const ON_RESET_PASSWORD_FAILURE = "ON_RESET_PASSWORD_FAILURE"

export const DO_MODAL_OPEN = "DO_MODAL_OPEN"
export const DO_MODAL_CLOSE = "DO_MODAL_CLOSE"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILURE = "GET_USER_FAILURE"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

export const ON_USER_LOGOUT_REQUEST = "ON_USER_LOGOUT_REQUEST"
export const ON_USER_LOGOUT_SUCCESS = "ON_USER_LOGOUT_SUCCESS" 

export const ON_VERIFY_ACCOUNT_REQUEST = "ON_VERIFY_ACCOUNT_REQUEST"
export const ON_VERIFY_ACCOUNT_SUCCESS = "ON_VERIFY_ACCOUNT_SUCCESS"
export const ON_VERIFY_ACCOUNT_FAILURE = "ON_VERIFY_ACCOUNT_FAILURE"

export const GET_COMPETITIONS_REQUEST = "GET_COMPETITIONS_REQUEST"
export const GET_COMPETITIONS_SUCCESS = "GET_COMPETITIONS_SUCCESS"
export const GET_COMPETITIONS_FAILURE = "GET_COMPETITIONS_FAILURE"

export const GET_COUPANS_REQUEST = "GET_COUPANS_REQUEST"
export const GET_COUPANS_SUCCESS = "GET_COUPANS_SUCCESS"
export const GET_COUPANS_FAILURE = "GET_COUPANS_FAILURE"

export const POST_CONTACT_US_REQUEST = "POST_CONTACT_US_REQUEST"
export const POST_CONTACT_US_SUCCESS = "POST_CONTACT_US_SUCCESS"
export const POST_CONTACT_US_FAILURE = "POST_CONTACT_US_FAILURE"